apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-robot-shop-namespace
spec:
  rules:
    - name: enforce-namespace
      match:
        resources:
          kinds:
            - Deployment
            - Service
            - PersistentVolumeClaim
      validate:
        message: "Resources must be created in the 'robot-shop' namespace."
        pattern:
          metadata:
            namespace: "robot-shop"
